env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  tsconfigRootDir: './'
  project: ['./tsconfig.json', './packages/*/tsconfig.json']
plugins:
  - react
  - '@typescript-eslint'
root: true
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".tsx"] }]
