env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:import/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  tsconfigRootDir: './'
  project: ['./tsconfig.json', './packages/*/tsconfig.json']
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
root: true
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".tsx"] }]
  'import/prefer-default-export': 'off'
  'import/no-default-export': 'error'
  'import/no-unresolved': 'off'
  'import/extensions': 'off'
